### ISSUE TITLE
throw error when there is no post with 'podcast' category

### ISSUE THREAD

**Issue by mehrad77** [owen8877/hexo-generator-podcast#2]
Hello and thank you for this plugin.
```
$ hexo server
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
TypeError: Cannot read property 'posts' of undefined
    at Hexo.module.exports (/hexoproject/node_modules/hexo-generator-podcast/lib/generator.js:44:60)
    at Hexo.tryCatcher (/hexoproject/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/hexoproject/node_modules/bluebird/js/release/method.js:15:34)
    at Promise.map.key (/hexoproject/node_modules/hexo/lib/hexo/index.js:336:26)
    at tryCatcher (/hexoproject/node_modules/bluebird/js/release/util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (/hexoproject/node_modules/bluebird/js/release/map.js:61:38)
    at MappingPromiseArray.PromiseArray._iterate (/hexoproject/node_modules/bluebird/js/release/promise_array.js:114:31)
    at MappingPromiseArray.init (/hexoproject/node_modules/bluebird/js/release/promise_array.js:78:10)
    at MappingPromiseArray._asyncInit (/hexoproject/node_modules/bluebird/js/release/map.js:30:10)
    at Async._drainQueue (/hexoproject/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/hexoproject/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/hexoproject/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

I just installed it by npm and this is what I got. What should I do?

**Comment by owen8877** [comment]
That is probably because there is no such a post with category 'podcast' (which is definitely a bug I need to fix). Maybe you can create a post with category 'podcast' shown in the [README.md](https://github.com/owen8877/hexo-generator-podcast#post-examplein-source_posts) ?

**Comment by owen8877** [comment]
Please update to `2.0.1`.

**Comment by mehrad77** [comment]
Oh! So that's it! 
Great work and really fast! 
Thank you!
